# Generated by Django 5.1.1 on 2024-09-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('service_type', models.CharField(choices=[('plumber', 'Plumber'), ('barber', 'Barber'), ('mechanic', 'Mechanic'), ('laundry', 'Laundry'), ('tutor', 'Tutor'), ('trade', 'Goods Exchange')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
