# Generated by Django 5.1.1 on 2024-09-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
