# Generated by Django 5.1.1 on 2024-09-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_serviceprovider_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='description',
            field=models.TextField(blank=True, default='No description'),
        ),
    ]
